#!/usr/bin/env bash

MACHINE=$1
USERDATAFILENAME=$2
IP=$3


# The root of the repo is given by the
# infrastructure-live/scritps/update-instance. We cannot get it with
# git rev-parse in that case because vm-images is a submodule.

if [ -z "$ROOT" ]; then
    ROOT=`git rev-parse --show-toplevel`
fi

NIXPKGS_VERSION=`cat ${ROOT}/nixpkgs_version`

if [ -z "$BUILD_HOST" ]; then
    BUILD_HOST_STR=""
else
    BUILD_HOST_STR="--build-host ${BUILD_HOST}"
fi


nixos-rebuild -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/${NIXPKGS_VERSION}.tar.gz\
              -I custom=${ROOT}/nix/pkgs\
              -I platform=${ROOT}/nix/nixos/machines/ami-platform.nix\
              -I nixos-config=${ROOT}/nix/nixos/machines/${MACHINE}.nix\
              -I user-data=${USERDATAFILENAME}\
              ${BUILD_HOST_STR} --target-host root@${IP}\
              switch
